### ISSUE TITLE
Не работает кнопка "Экспорт"

### ISSUE THREAD

**Issue by GalimzyanovDanil** [Paulo1312/ss_to_json_outline_rust#2]
На сайте `https://paulo1312.github.io/ss_to_json/`  не работает кнопка экспорт после вставки конфига

**Comment by Paulo1312** [comment]
Привет. Если можно - можешь, пожалуйста, скинуть формат своего конфига? (Убери адрес, порт, пароль и т.д.). Скорее всего - мой скрипт (пока что) не "есть " конфиги твоего формата. Если так, то я могу это исправить

Можешь отправить тут, в личку, в дельту или на почту

**Comment by GalimzyanovDanil** [comment]
ss://{что то тут}@{здесь адрес судя по всему}:{порт}/?outline=7&prefix=%11%11%11%11%11%11%11%11#111+%11%11%11%11%11%11%11%11%11%11%11%11%11%11%11%11+%11%11%11%11%11%11%11%11%11%11%11%11%11%11

@Paulo1312 Как то так

**Comment by Paulo1312** [comment]
Вроде пофиксил. Проверишь?
@GalimzyanovDanil

**Comment by GalimzyanovDanil** [comment]
Все заработало. Спасибо
